[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["openzeppelin-contracts/=lib/openzeppelin-contracts/"]

# CI uses FOUNDRY_PROFILE=ci
[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["openzeppelin-contracts/=lib/openzeppelin-contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
